### PR TITLE
Updated for gadi and conda environments

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Also added a section on manifests.

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
I'll merge this, hope that is ok @marshallward

**Comment by marshallward** [comment]
Can you tag the version that was presented?

**Comment by aidanheerdegen** [comment]
Sure.

**Comment by aidanheerdegen** [comment]
https://github.com/payu-org/payucourse/tree/2018_present

**Comment by aidanheerdegen** [comment]
Something is b0rk3d. I'll strip out the NCI branding too if that is ok, seeing as neither of us is associated with them in an official capacity.

**Comment by marshallward** [comment]
Excellent idea :D

**Pull request merged**
